### ISSUE TITLE
VSCode plugin still supported?

### ISSUE THREAD

**Issue by why-not-try-calmer** [haskell/stylish-haskell#406]
Just tried it to no avail:
```
[2022-06-24 13:02:52.159] [exthost] [error] [haskell.haskell] provider FAILED
[2022-06-24 13:02:52.159] [exthost] [error] Error: No plugin enabled for STextDocumentFormatting, available: []
	at /home/hades/.vscode/extensions/haskell.haskell-2.2.0/dist/extension.js:1:467090
	at /home/hades/.vscode/extensions/haskell.haskell-2.2.0/dist/extension.js:1:467384
	at Immediate.<anonymous> (/home/hades/.vscode/extensions/haskell.haskell-2.2.0/dist/extension.js:1:467749)
	at processImmediate (node:internal/timers:464:21)
```
With mostly default settings on VSCode (except of course for a running and working HLS installed from ghcup and picked up by the corresponding HLS VSCode extension. (`formulu` works fine for me on this very setup).

So the question is: Is this plugin still supported?

**Comment by drsooch** [comment]
https://github.com/haskell/haskell-language-server owns the `stylish-haskell-plugin` integration

**Comment by why-not-try-calmer** [comment]
Thanks
